adobecom/bacom

styles/styles.css
MWPW-112696
Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/golden-state-warriors-case-study
After: https://patch-styles--bacom--adobecom.hlx.page/customer-success-stories/golden-state-warriors-case-study
=> Adding utility styles for customer stories

blocks/event-speakers/event-speakers.css, blocks/event-speakers/event-speakers.js, package-lock.json, test/blocks/event-speakers/event-speakers.test.js
- Add Event Speakers block
[MWPW-114644](https://jira.corp.adobe.com/browse/MWPW-114644)
https://event-speakers--bacom--adobecom.hlx.page/drafts/methomas/event-speakers
=> Add event speakers block MWPW-114644

.github/workflows/run-tests.yaml
- Add workflow for code coverage bot
=> Add code coverage bot

blocks/stats/stats.css
Revert accidental commit to origin branch
=> Revert stats logo styling

blocks/stats/stats.js, scripts/scripts.js
Remove optionals.
Remove module-level dynamic imports.
=> Fix iOS 14 Safari

blocks/stats/stats.js
* Added our milo analytics to the `stats` block
Resolves: no jira ticket 
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/redtag-ca-case-study?martech=off
- After: https://stats-analytics--bacom--adobecom.hlx.page/customer-success-stories/redtag-ca-case-study?martech=off
Testing notes
Inspect the DOM to ensure the following data attributes are included in the stats block. (daa-im, daa-lh, daa-ll) see utils/analytics.md for more details.
=> Added analytics to stats block

scripts/scripts.js
* Add stage api key and analytics report suite ID for pdf viewSDK
Resolves: [MWPW-115380](https://jira.corp.adobe.com/browse/MWPW-115380)
=> MWPW-115380 Add stage pdf viewSDK api key and analytics ID

blocks/stats/stats.js
* Have a fallback path for when milo moves the analytics code
Resolves: [MWPW-118484](https://jira.corp.adobe.com/browse/MWPW-118484)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/abb-case-study?martech=off
- After: https://move-analytics--bacom--adobecom.hlx.page/customer-success-stories/abb-case-study?martech=off
=> MWPW-118484 - Rename analytics

blocks/stats/stats.js, scripts/scripts.js
* Add edge ids for analytics reporting
Resolves: [MWPW-117934](https://jira.corp.adobe.com/browse/MWPW-117934)
**Test w/ BACOM Changes**
- After: https://edge-ids--bacom--adobecom.hlx.page/customer-success-stories/princess-cruises-case-study
**Test w/ BACOM & Milo Changes**
- After: https://edge-ids--bacom--adobecom.hlx.page/customer-success-stories/princess-cruises-case-study?milolibs=edge-ids
**Test w/ Milo Changes**
- After: https://main--bacom--adobecom.hlx.page/customer-success-stories/princess-cruises-case-study?milolibs=edge-ids
=> MWPW-117934 - Add edge id configs

scripts/scripts.js, styles/styles.css, styles/variables.css
* Add JP font
* Enable JP locale
Resolves: [MWPW-118659](https://jira.corp.adobe.com/browse/MWPW-118659)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/jp/customer-success-stories/geniee-case-study?martech=off
- After: https://jp-font--bacom--adobecom.hlx.page/jp/customer-success-stories/geniee-case-study?martech=off
=> MWPW-118659 Add JP Font

package.json, test/blocks/stats/stats.test.js, web-test-runner.config.mjs
* Add test runner config
* Add first Stats test
* Shows more accurate test coverage number
**Test URLs:**
- After: https://methomas-stats-test--bacom--adobecom.hlx.page/?martech=off
=> Add test runner config and first Stats test

test/blocks/stats/stats.test.js
* Add test for Stats block for 100% Stats block coverage
**Test URLs:**
Doesn't apply
=> Improve Stats test coverage

blocks/comparison/comparison.css, blocks/comparison/comparison.js, test/blocks/comparison/comparison.test.js, test/blocks/comparison/mocks/body.html
* Adding Comparison table block with accessible headers
* Button styling will come from Milo auto-buttons
* Still waiting for icon design
Resolves: [MWPW-115385](https://jira.corp.adobe.com/browse/MWPW-115385)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/bmarshal/comparison-table?martech=off
- After: https://bmarshal-comparison--bacom--adobecom.hlx.page/drafts/bmarshal/comparison-table?martech=off
=> MWPW-115385 Adding Comparison table block

styles/styles.css
* Add custom "text list" styles for text block to satisfy webinar requirements
Resolves: [MWPW-119015](https://jira.corp.adobe.com/browse/MWPW-119015)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/event-speakers?martech=off
- After: https://methomas-text-list--bacom--adobecom.hlx.page/drafts/methomas/event-speakers?martech=off
=> MWPW-119015 Text List Styles

scripts/scripts.js
* Enable georouting
Resolves: [MWPW-121766](https://jira.corp.adobe.com/browse/MWPW-121766)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/coca-cola-case-study?martech=off
- After: https://methomas-geo-modal--bacom--adobecom.hlx.page/drafts/methomas/coca-cola-case-study?martech=off
- After: https://methomas-geo-modal--bacom--adobecom.hlx.page/de/drafts/methomas/coca-cola-case-study?martech=off
- After: https://methomas-geo-modal--bacom--adobecom.hlx.page/kr/drafts/methomas/coca-cola-case-study?martech=off
=> MWPW-121766 - Enable Georouting

scripts/scripts.js
* Disables GeoRouting
Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/de/drafts/methomas/coca-cola-case-study?martech=off
- After: https://disable-georouting--bacom--adobecom.hlx.page/de/drafts/methomas/coca-cola-case-study?martech=off
=> Disable GeoRouting

.husky/pre-commit, README.md
* Adding tests to precommit hook
=> Adding test to precommit hooks

.eslintrc.js, blocks/tree-view/tree-view.js, package-lock.json, package.json, test/blocks/comparison/comparison.test.js, test/blocks/event-speakers/event-speakers.test.js, test/blocks/stats/stats.test.js, test/blocks/tree-view/tree-view.test.js, tools/sidekick/config.js
* Add package: eslint-plugin-chai-friendly
* Allow console in test folder
* Cleanup lint errors
Resolves: #51
=> Improve test linting

scripts/scripts.js
- This PR should be merged before Milo PR - https://github.com/adobecom/milo/pull/396
Resolves: MWPW-124277
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/kr/customer-success-stories
- After: https://link-transform--bacom--adobecom.hlx.page/kr/customer-success-stories?milolibs=link-transform
=> MWPW-124277: Link Localization support for www.adobe.com

README.md
* Add link to contributing doc in readme for greater visibility
Resolves: #71 
**Test URLs:**
N/A
=> Link contributing doc in readme

scripts/utils.js
Use the cached version of milo in non-prod scenarios.
=> Move to live

scripts/scripts.js
* Adding AutoBlocks for Embedded Product Tour using https://github.com/adobecom/milo/pull/426
Resolves: [MWPW-123566](https://jira.corp.adobe.com/browse/MWPW-123566)
**Test URLs:**
- Before: https://bmarshal-embed-product-tour--bacom--adobecom.hlx.page/drafts/bmarshal/embed-product-tour?martech=off
- After: https://bmarshal-embed-product-tour--bacom--adobecom.hlx.page/drafts/bmarshal/embed-product-tour?milolibs=bmarshal-embed-product-tour&martech=off
=> MWPW-123566 Adding AutoBlocks for Embedded Product Tour

blocks/tree-view/tree-view.css, blocks/tree-view/tree-view.js, test/blocks/tree-view/tree-view.test.js
* Change tree view accordion classes to avoid style collision
Resolves: [MWPW-125397](https://jira.corp.adobe.com/browse/MWPW-125397)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/tree-view-accordion?martech=off
- After: https://methomas-tree-view-accordion--bacom--adobecom.hlx.page/drafts/methomas/tree-view-accordion?martech=off
=> MWPW-125397 Fix Tree View Accordion Styles

blocks/chat-cta/chat-cta.css, blocks/chat-cta/chat-cta.js, blocks/event-speakers/event-speakers.css, package-lock.json, test/blocks/chat-cta/chat-cta.test.js, test/blocks/chat-cta/mocks/body.html
* Adds a contact us block for Bacom use
Resolves: [MWPW-123363](https://jira.corp.adobe.com/browse/MWPW-123363)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/slavin/hyundai-mnsoft-case-study?martech=off
- After: https://sticky-chat-cta--bacom--adobecom.hlx.page/drafts/slavin/hyundai-mnsoft-case-study?martech=off
=> MWPW-123363 Contact Us Block

.github/codeql/codeql-config.yml, .github/workflows/codeql.yml
* Add codeql to git workflow for code scanning on PRs
Resolves: #59 
**Test URLs:**
N/A
=> Add codeql

tools/sidekick/config.json
* Enable Locales tool in sidekick
Resolves: #89 
**Test URLs:**
N/A
=> Enable Locales tool in sidekick

blocks/chat-cta/chat-cta.css, blocks/chat-cta/chat-cta.js, scripts/scripts.js, test/blocks/chat-cta/chat-cta.test.js
This reverts commit 03f7a61c96722d9162f34c0887a06cff8318d080.
Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- After: https://<branch>--bacom--adobecom.hlx.page/?martech=off
=> Revert "Enable cta config (#91)"

helix-query.yaml
* Index customer stories pages for all locales
* Includes properties breadcrumb home, caas tags, and defaults
Resolves: [MWPW-129144](https://jira.corp.adobe.com/browse/MWPW-129144)
**Test URLs:**
N/A
=> MWPW-129144 Index customer stories ROW

blocks/chat-cta/chat-cta.css, blocks/chat-cta/chat-cta.js, helix-query.yaml, scripts/scripts.js, test/blocks/chat-cta/chat-cta.test.js
Update stage branch with latest changes from main for the Resources A/B test
=> Update Stage Branch

helix-query.yaml
* Add video-only customer success stories to new index (See bottom of file)
* Clean up query index
Resolves: [MWPW-129025](https://jira.corp.adobe.com/browse/MWPW-129025)
**Test URLs:**
N/A
=> MWPW-129025 Index intl customer story videos

helix-query.yaml
* Change CSS video index to use default properties only
* Intended to fix index
Resolves: [MWPW-129025](https://jira.corp.adobe.com/browse/MWPW-129025)
**Test URLs:**
N/A
=> MWPW-129025 Fix video index

.github/workflows/run-nala.yaml
Adding the Nala workflow to Github actions so that we can run Nala tests against PRs.
Resolves: [MWPW-129461](https://jira.corp.adobe.com/browse/MWPW-129461)
**Test URLs:**
N/A
=> Adding Nala workflow to Github actions

scripts/scripts.js
* Fix layout shift caused by delayed loading of css
Resolves: [MWPW-128620](https://jira.corp.adobe.com/browse/MWPW-128620)
**Test URLs:**
- Before: https://faas-styles--bacom--adobecom.hlx.page/resources/guides/solve-the-pain-of-mixing-agile-and-waterfall?martech=off
- After: https://bmarshal-faas-styles--bacom--adobecom.hlx.page/resources/guides/solve-the-pain-of-mixing-agile-and-waterfall?martech=off
=> Fix layout shift for FaaS

styles/faas.css
* Adding styles for FaaS Form 115, cleanup will come later.
Resolves: [MWPW-128620](https://jira.corp.adobe.com/browse/MWPW-128620)
**Test URLs:**
- Before: https://faas-styles--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-115?martech=off
- After: https://bmarshal-faas-styles--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-115?martech=off
=> MWPW-128620 FaaS Form 115 Styles

styles/faas.css
* Reorganize styles into 1 column and 2 column layouts
* Consolidate and update styles to match designs
Resolves: [MWPW-129587](https://jira.corp.adobe.com/browse/MWPW-129587)
**Test URLs:**
- Before: https://faas-styles--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-21?martech=off
- After: https://bmarshal-faas-styles--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-21?martech=off
- Before: https://faas-styles--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-21-clearbit?martech=off
- After: https://bmarshal-faas-styles--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-21-clearbit?martech=off
- Before: https://faas-styles--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-115?martech=off
- After: …
=>  MWPW-129587 FaaS Styles

scripts/scripts.js, styles/faas.css
* 2 Columns FaaS Styles for 79, 63, 21
* 2 Columns Clearbit FaaS Enabled Styles for 79, 21
* 1 Column FaaS Styles for 115
* Fix layout shift for BACOM FaaS styles
Resolves: [MWPW-128620](https://jira.corp.adobe.com/browse/MWPW-128620), [MWPW-129587](https://jira.corp.adobe.com/browse/MWPW-129587), & [MWPW-129585](https://jira.corp.adobe.com/browse/MWPW-129585)
**Columns Block Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-115
- After: https://faas-styles--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-115
- Before: https://main--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-21-clearbit
- After: https://faas-styles--bacom--adobecom.hlx.page/drafts/bmarshal/faas/columns-block/faas-21-clearbit
- …
=> FaaS Styles feature branch to Main

helix-query.yaml
* Add US resource pages to query index with faas url
Resolves: [MWPW-130076](https://jira.corp.adobe.com/browse/MWPW-130076)
**Test URLs:**
N/A
=> MWPW-130076 US Resource Query Index

blocks/faas-decode/faas-decode.css, blocks/faas-decode/faas-decode.js
* Add missed column "Internal Campaign ID" to report
* Keep "Onsight Campaign ID" column
Resolves: [MWPW-131411](https://jira.corp.adobe.com/browse/MWPW-131411)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/docs/reports/faas-us-resources?martech=off
- After: https://methomas-report-bug--bacom--adobecom.hlx.page/docs/reports/faas-us-resources?martech=off
=> MWPW-131411 Add internal campaign id to report

scripts/scripts.js
* Removes load delayed as per Narcis comment on slack 
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories
- After: https://remove-load-delayed--bacom--adobecom.hlx.page/?martech=off
- After https://remove-load-delayed--bacom--adobecom.hlx.page/customer-success-stories
=> Removing load delayed as per Narcis comment on Slack

styles/faas.css
* Align FaaS checkbox 
Resolves: [MWPW-131894](https://jira.corp.adobe.com/browse/MWPW-131894)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/resources/personalization-at-scale-report?martech=off
- After: https://bmarshal-form-checkbox--bacom--adobecom.hlx.page/resources/personalization-at-scale-report?martech=off
=> MWPW-131894 fix checkbox height

helix-query.yaml
* Add robots property so that noindex pages can be filtered.
* https://www.hlx.live/developer/indexing#enforcing-noindex-configuration-with-custom-index-definitions
Resolves: [MWPW-132487](https://jira.corp.adobe.com/browse/MWPW-132487)
Test URLs:
N/A
=> MWPW-132487 Fix noindex pages in sitemap

tools/sidekick/config.json
* Add Consumer Tags to Sidekick
Resolves: [MWPW-130312](https://jira.corp.adobe.com/browse/MWPW-130312)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/tools/tag-selector?martech=off
- After: https://bmarshal-consumer-tags--bacom--adobecom.hlx.live/tools/tag-selector?martech=off
=> MWPW-130312 Adding Consumer Tags

helix-query.yaml
* Add homepage to query index
Resolves: [MWPW-135488](https://jira.corp.adobe.com/browse/MWPW-135488)
**Test URLs:**
N/A
=> MWPW-135488 Add homepage to query index

blocks/form/form.css
* Modify form heading from h2 to h3 
Resolves: [SITES-15958](https://jira.corp.adobe.com/browse/SITES-15958)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/drafts/swbarman/?martech=off
- After: https://main--bacom--swetabar.hlx.live/drafts/swbarman/?martech=off
=> [SITES-15958] Modify the heading for the franklin form component from h2 to h3

blocks/form/form.css, blocks/form/form.js, test/blocks/form/form.test.js, test/blocks/form/mocks/body.html
* re-style button to use static white Spectrum pattern
* add support for hidden fields
Resolves: 
* [SITES-15861](https://jira.corp.adobe.com/browse/SITES-15861)
* [SITES-16058](https://jira.corp.adobe.com/browse/SITES-16058)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/swbarman/?martech=off
- After: https://headless-form--bacom--arumsey.hlx.page/drafts/swbarman/?martech=off
**Default static white button**
**Hover static white button**
**Invalid email**
**Success message**
=> [TBYB] Author franklin form block on the bacom headless page

styles/styles.css
=> Revert "Grid width styles revert temp fix, now coming in from Milo"

tools/sidekick/config.json
Resolves: [MWPW-140319](https://jira.corp.adobe.com/browse/MWPW-140319)
=> MWPW-140319: Add floodgate option to sidekick tools menu

blocks/faas-decode/faas-decode.js, blocks/tree-view/tree-view.js
* Removing space to tags
Resolves: [MWPW-138026](https://jira.corp.adobe.com/browse/MWPW-138026)
**Test URLs:**
- After: https://bmarshal-lana-logs--bacom--adobecom.hlx.live/?martech=off
=> MWPW-138026 Add tags to lana logs

.github/workflows/fg-sync-repos.yml
* Adds workflow action for FG sync
Resolves: [MWPW-140270](https://jira.corp.adobe.com/browse/MWPW-140270)
**Test URLs:**
- After: https://add-bac om-pink-action--bacom--adobecom.hlx.live/?martech=off
=> MWPW-140270: Adding the fg sync workflow

helix-query.yaml
* Add publish date to all query indexes
Resolves: [MWPW-138379](https://jira.corp.adobe.com/browse/MWPW-138379)
**Test URLs:**
N/A
=> MWPW-138379 Add publish date to all query indexes

scripts/aa-university.js, scripts/scripts.js, test/helpers/generalHelpers.js, test/scripts/aa-university.test.js, test/scripts/mocks/body.html, web-test-runner.config.mjs
* Enable AA University registration for Marketo (by metadata)
Resolves: [MWPW-141206](https://jira.corp.adobe.com/browse/MWPW-141206)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/marketo-aa-university
- After: https://methomas-aa-sandbox--bacom--adobecom.hlx.page/drafts/methomas/marketo-aa-university
=> MWPW-141206 AA University in Marketo

helix-query.yaml, helix-sitemap.yaml
* Remove MT and CY_EN sitemaps
Resolves: [MWPW-144537](https://jira.corp.adobe.com/browse/MWPW-144537)
**Test URLs:**
N/A
=> MWPW-144537 Remove MT and CY_EN sitemaps

styles/styles.css
Reverts adobecom/bacom#181
- Before: https://main--bacom--adobecom.hlx.page/fr/
- After: https://revert-181-cls-fix--bacom--adobecom.hlx.page/fr/
=> Revert "MWPW-143973: CLS Issue with Grid Width"

.kodiak/config.yaml, styles/styles.css
- https://github.com/adobecom/bacom/pull/187
- https://github.com/adobecom/bacom/pull/188
=> Release stage to main

.github/workflows/fg-sync-repos.yml
Resolves: [MWPW-151674](https://jira.corp.adobe.com/browse/MWPW-151674)
=> MWPW-151674: Branch level support for FG repo-sync

.github/workflows/run-tests.yaml
* Update unit test workflow to match milo
* Unit tests should run on PR to stage
Resolves: #210
=> Update unit test workflow #220

tools/sidekick/config.json
Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-NUMBER)
**Test URLs:**
- After: https://<branch>--bacom--adobecom.hlx.live/?martech=off
=> add graybox promote

.github/workflows/run-nala.yaml
* Resolves: [MWPW-153060](https://jira.corp.adobe.com/browse/MWPW-153060)
* Fixes run-nala Github action job
**Test URLs:**
- Before: https://stage--bacom--adobecom.hlx.live/?martech=off
- After: https://stage--bacom--adobecom.hlx.live/?martech=off
=> [MWPW-153060] Fix run nala action job

helix-query.yaml
* Add `/industries/` path to index for sitemap for upcoming launch
Resolves: [MWPW-152312](https://jira.corp.adobe.com/browse/MWPW-152312)
**Test URLs:**
N/A
=> MWPW-152312 Add industries path to index

.github/workflows/run-nala.yaml, .github/workflows/run-tests.yaml, helix-query.yaml, scripts/scripts.js
=> [Release] Stage to Main

styles/styles.css
* Temporary fix while we wait for https://github.com/adobecom/milo/pull/2588 to be released. 
* To be reverted after scheduled release on Monday.
Resolves: [MWPW-154562](https://jira.corp.adobe.com/browse/MWPW-154562)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/resources/videos/marketo-product-tour?martech=off
- After: https://bmarshal-marketo-margin--bacom--adobecom.hlx.live/resources/videos/marketo-product-tour?martech=off
=> MWPW-154562 Fix resource form margins

styles/styles.css
* https://github.com/adobecom/bacom/pull/224
**Test URLs:**
- After: https://stage--bacom--adobecom.hlx.live/?martech=off
Stage: https://business.stage.adobe.com/
=> [Release] Stage to Main 

.github/workflows/fg-sync-repos.yml
* Fix branch name
Resolves: [MWPW-145389](https://jira.corp.adobe.com/browse/MWPW-145389)
**Test URLs:**
N/A
=> MWPW-145389 Push sync for floodgate and graybox

.github/workflows/run-e2e-daily.yaml
Added step to checkout the nala repo. 
Resolves: [MWPW-155726](https://jira.corp.adobe.com/browse/MWPW-155726)
**Test URLs:**
- After: https://daily-workflow--bacom--adobecom.hlx.live/?martech=off
=> Daily workflow

.github/workflows/run-e2e-daily.yaml
Resolves: [MWPW-155726](https://jira.corp.adobe.com/browse/MWPW-155726)
**Test URLs:**
- After: https://daily-workflow-fixes--bacom--adobecom.hlx.live/?martech=off
=> Fixed nala checkout.

.github/workflows/run-e2e-daily.yaml
Updating the runner in the daily e2e workflow to ubuntu. 
Resolves: [MWPW-156128](https://jira.corp.adobe.com/browse/MWPW-156128)
**Test URLs:**
- After: https://daily-runner--bacom--adobecom.hlx.live/?martech=off
=> Updating the runner in the daily e2e workflow

helix-query.yaml
*  Index CaaS URLs so that they may be validated
Resolves: [MWPW-158345](https://jira.corp.adobe.com/browse/MWPW-158345)
**Test URLs:**
N/A
=> MWPW-158345 Index CaaS URLs

helix-query.yaml
* index multiple CaaS links
Resolves: [MWPW-158345](https://jira.corp.adobe.com/browse/MWPW-158345)
**Test URLs:**
N/A
=> MWPW-158345 index multiple CaaS links

helix-sitemap.yaml
* Add Blog sitemap to main sitemap
Resolves: [MWPW-157692](https://jira.corp.adobe.com/browse/MWPW-157692)
**Test URLs:**
N/A
=> MWPW-157692 Add Blog Sitemaps

scripts/aa-university.js
* Swaps AA endpoint 
Resolves: [MWPW-162959](https://jira.corp.adobe.com/browse/MWPW-162959)
**Test URLs:**
- After: https://swap-aa-endpoint--bacom--adobecom.hlx.live/?martech=off
- Before: https://main--bacom--adobecom.hlx.live/resources/adobe-analytics-sandbox
- After: https://swap-aa-endpoint--bacom--adobecom.hlx.live/resources/adobe-analytics-sandbox
=> MWPW-162959: Swap aa endpoint

.github/workflows/import/index.js, .github/workflows/listen-to-publish-events.yaml
Follow up for https://github.com/adobecom/bacom/pull/278 to post to #da-rolling-import so we get notified in case of import failures.
Resolves: [MWPW-164826](https://jira.corp.adobe.com/browse/MWPW-164826)
**Test URLs:**
- Before: https://stage--bacom--adobecom.hlx.live/?martech=off
- After: https://slack-webhook-for-rolling-import--bacom--adobecom.hlx.live/?martech=off
=> Slack webhook for rolling import

scripts/scripts.js
* Updates our config with the new css sheet for thai characters
Resolves: [MWPW-166191](https://jira.corp.adobe.com/browse/MWPW-166191)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/th_th/?martech=off
- After: https://update-thai-lang--bacom--adobecom.hlx.live/th_th/?martech=off
=> MWPW-166191 Update Thai font

scripts/scripts.js
* Add configuration for Jarvis chat
Resolves: [MWPW-168712](https://jira.corp.adobe.com/browse/MWPW-168712)
**Test URLs:**
- After: https://jarvis--bacom--adobecom.aem.live/?martech=off
Note: This is not testable before stage because of domain allowlisting
=> MWPW-168712 Configure Jarvis Chat

helix-query.yaml
adding /ai directory
Resolves: [MWPW-169992](https://jira.corp.adobe.com/browse/MWPW-169992)
**Test URLs:**
- After: https://<branch>--bacom--adobecom.aem.live/?martech=off
=> Update helix-query.yaml to update /ai 

scripts/scripts.js
* Update invalid lana tag
Resolves: [MWPW-164710](https://jira.corp.adobe.com/browse/MWPW-164710)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/404-monitoring?lanadebug
- After: https://lana-404--bacom--meganthecoder.hlx.page/drafts/methomas/404-monitoring?lanadebug
=> MWPW-164710 Update invalid lana tag

tools/sidekick/config.json
* #311 
**Test URLs:**
- After: https://stage--bacom--adobecom.aem.live/?martech=off
=> MWPW-166673 [Helix 5 Migration] Update sidekick urls (#311)

blocks/cta-widget-test/cta-widget-test.css, blocks/cta-widget-test/cta-widget-test.js, scripts/scripts.js
Resolves: [MWPW-166694](https://jira.corp.adobe.com/browse/MWPW-166694)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/resources/contact-us-chat-test?martech=off
- After: https://cta-widget-test-update--bacom--adobecom.hlx.live/resources/contact-us-chat-test?martech=off
=> MWPW-166694: Modifying Chat Widget for Testing 

scripts/scripts.js
* Update production pdf client id
Resolves: [MWPW-147773](https://jira.corp.adobe.com/browse/MWPW-147773)
**Test URLs:**
Because the client ids are domain-specific, this isn't testable prior to release.
=> MWPW-147773 Update PDF Client ID for Prod

head.html
* Using metadata, adds hreflang links to the head of the document 
Resolves: [MWPW-169763](https://jira.corp.adobe.com/browse/MWPW-169763)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/drafts/slavin/aem-sites?martech=off
- After: https://add-hreflang-to-head--bacom--adobecom.hlx.live/drafts/slavin/aem-sites?martech=off
=> MWPW-169763: Add hreflang to head

head.html
- https://github.com/adobecom/bacom/pull/310
**Test URLs:**
- After: https://<branch>--bacom--adobecom.aem.live/?martech=off
=> Release [Stage to Main]

blocks/cta-widget-test/cta-widget-test.js
* Updates event to 'triggered' and removes timeout
Resolves: [MWPW-166694](https://jira.corp.adobe.com/browse/MWPW-166694)
**Test URLs:**
- After: https://chat-test-update--bacom--adobecom.aem.live/?martech=off
=> MWPW-166694: Update event to 'triggered' and remove timeout

.github/workflows/import/daFetch.js, .github/workflows/import/index.js, .github/workflows/listen-to-publish-events.yaml
Remove redirects.xlsx from Auto-importer https://jira.corp.adobe.com/browse/MWPW-173107
Update DA rolling import to import media https://jira.corp.adobe.com/browse/MWPW-173301
Support bulk publish events https://jira.corp.adobe.com/browse/MWPW-173460
Feature parity with the changes introduced in 
https://github.com/da-sites/nexter/commit/fe1e315ee2ae7002dd18e4e93b962c9ca69b1aa9 & https://github.com/da-sites/nexter/commit/09a4b65be971ab5649256473c678927866ae64f3 to fix supporting assets and importing them to DA
The import log now looks something like this
1. Fetch page
2. Fetch assets
3. Import all the assets
4. Preview & Publish all the imported assets
5. Import page
6. Preview & Publish the page
```
Started path:  https://main--bacom--adobecom.aem.live/customer-success-stories
fetched …
```
=> Various auto importer improvements

.github/workflows/import/daFetch.js, .github/workflows/listen-to-publish-events.yaml
Fixes token handling for multiple documents
**Test URLs:**
- After: https://fix-importer--bacom--adobecom.aem.live/?martech=off
=> Fix token handling

404.html
* Adds 404 metadata to page to use local 404
Resolves: [MWPW-171824](https://jira.corp.adobe.com/browse/MWPW-171824)
**Test URLs:**
- After: https://404-update--bacom--adobecom.aem.live/?martech=off
**To see 404 Changes**
- Before: https://main--bacom--adobecom.aem.page/this-isnt-a-page?martech=off
- After: https://404-update--bacom--adobecom.aem.page/this-isnt-a-page?martech=off
=> MWPW-171824 - Updating 404.html to use Local method

styles/styles.css
* Fixes chat bot overlapping new mega menu
* Also fixes overlap on change region modal
Resolves: [MWPW-172504](https://jira.corp.adobe.com/browse/MWPW-172504)
**Test URLs:**
Note: Chat can only be tested on business.stage
- After: https://chat-gnav--bacom--meganthecoder.aem.live/?martech=off
https://business.stage.adobe.com/products/marketo.html?newNav=true
=> MWPW-172504 Fix chat overlapping mega menu

scripts/scripts.js
* Add helpx.adobe.com to config for link localization
* Add helpx.adobe.com to config for stage link transformation
Resolves: [MWPW-174813](https://jira.corp.adobe.com/browse/MWPW-174813)
**Test URLs:**
- Before: https://main--bacom--adobecom.aem.page/bg/drafts/sneha/helpx-link-transformation?martech=off
- After: https://helpx--bacom--meganthecoder.aem.page/bg/drafts/sneha/helpx-link-transformation?martech=off
=> MWPW-174813 Auto-localize Helpx links
