adobecom/bacom

blocks/event-speakers/event-speakers.css
- Fix underline safari bug for event speakers
Ticket: [MWPW-116886](https://jira.corp.adobe.com/browse/MWPW-116886)
Before: https://main--bacom--adobecom.hlx.page/docs/library/event-speakers
After: https://event-speakers-underline--bacom--adobecom.hlx.page/docs/library/event-speakers
=> Fix underline safari bug for event speakers MWPW-116886

blocks/stats/stats.css
* Adjusted Stats logo size to be smaller
* Adjusted Stats icon in the second column to be smaller.
Resolves: [DOTCOM-72228](https://jira.corp.adobe.com/browse/DOTCOM-72228)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/sage-case-study?martech=off
- After: https://adjust-stats-logo-icon--bacom--adobecom.hlx.page/customer-success-stories/sage-case-study?martech=off
=> Stats logo and icons wrong size

blocks/stats/stats.css
Description: 
Quick bug fix I caused in a bulk update. This puts links in the stats > solution section as they were. 
Test URLs:
https://main--bacom--adobecom.hlx.page/customer-success-stories/helly-hansen-case-study
https://stats-links-patch--bacom--adobecom.hlx.page/customer-success-stories/helly-hansen-case-study
=> block display for stats links in solutions class

blocks/stats/stats.css
Resolves styling for [MWPW-119641](https://jira.corp.adobe.com/browse/MWPW-119641)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/jp/customer-success-stories/abematv-case-study?martech=off
- After: https://bradjohn-stats-list-style--bacom--adobecom.hlx.page/jp/customer-success-stories/abematv-case-study?martech=off
=> Remove list style for product lists on customer stories

scripts/scripts.js
* Move PDF Viewer client ids into env-specific config
Resolves: [MWPW-120502](https://jira.corp.adobe.com/browse/MWPW-120502)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/pdf-viewsdk?martech=off
- After: https://methomas-pdf-stage-config--bacom--adobecom.hlx.page/drafts/methomas/pdf-viewsdk?martech=off&milolibs=methomas-move-pdf-config
Note: With the feature branch url, the PDF will show an error "Preview not available: This application domain is not authorized..." because the Viewer's client id is specifically for "main--bacom--adobecom.hlx.page". We'll verify once it's merged into main. Any other errors should be flagged though.
=> MWPW-120502 - PDF Viewer Config

styles/styles.css
* Align icon headings with h2
Resolves: [MWPW-118043](https://jira.corp.adobe.com/browse/MWPW-118043)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/bmarshal/column-icons?martech=off
- After: https://bmarshal-align-icons--bacom--adobecom.hlx.page/drafts/bmarshal/column-icons?martech=off
=> MWPW-118043 Align icon headings with h2

blocks/comparison/comparison.css
* Remove background transparency for tablet and mobile to prevent text overlap.
Resolves: [MWPW-121612](https://jira.corp.adobe.com/browse/MWPW-121612)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/denli/comparison-table?martech=off
- After: https://bmarshal-comparison-fixes--bacom--adobecom.hlx.page/drafts/denli/comparison-table?martech=off
=> MWPW-121612 comparison table header fixes

scripts/scripts.js
* Add live (.hlx.live) and prod (business.adobe.com) credentials for the PDF viewSDK
Resolves: [MWPW-118568](https://jira.corp.adobe.com/browse/MWPW-118568)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/pdf-cred-prod?martech=off
- After: https://methomas-pdf-prod-creds--bacom--adobecom.hlx.page/drafts/methomas/pdf-cred-prod?martech=off
Note: The pdf viewer will show an error on the test page because the creds work for the main branch url only
=> MWPW-118568 PDF viewSDK Live/Prod Credentials

styles/styles.css, styles/variables.css
* Japan font is now enabled by Milo https://github.com/adobecom/milo/pull/370
Resolves: [MWPW-123237](https://jira.corp.adobe.com/browse/MWPW-123237)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/jp/customer-success-stories/pga-tour-case-study?martech=off
- After: https://bmarshal-jp-font--bacom--adobecom.hlx.page/jp/customer-success-stories/pga-tour-case-study?martech=off
=> MWPW-122331 JP font loaded from Milo

blocks/comparison/comparison.js, scripts/scripts.js, web-test-runner.config.mjs
* Fixing broken test for comparison
Scripts.js is the only file without 100% coverage. All three functions within the file are:
- crucial to basic page rendering
- called as IIFEs
It would not make sense to export these functions just to test them, and their functionality is core to our site working properly, so one assumes it would be noticed if they were broken.
=> increase-code-coverage 

scripts/scripts.js
* Note that the lana file is not loaded until `window.lana.log` has been called, so there should be no changes to performance.
**Test URLs:**
- After: https://c3-initlana--bacom--adobecom.hlx.page/?martech=off
=> Init Lana for Bacom

helix-query.yaml
* Adding index property for CaaS Tags
Resolves: [MWPW-123771](https://jira.corp.adobe.com/browse/MWPW-123771)
**Test URLs:**
- After: https://bmarshal-caas-index--bacom--adobecom.hlx.page/?martech=off
=> MWPW-123771 index CaaS tags

scripts/scripts.js
Adding the Vietnamese locales to bacom locale list
Resolves: MWPW-120796
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/vn_en/customer-success-stories/umobile-case-study
- After: https://link-transform--bacom--adobecom.hlx.page/vn_en/customer-success-stories/umobile-case-study
=> MWPW-120796: Link Localization support for VN_EN and VN_VI

blocks/event-speakers/event-speakers.js, blocks/stats/stats.js, blocks/tree-view/tree-view.js, test/blocks/stats/stats.test.js
* NOTE: This PR relates directly to [#503 in the milo repo](https://github.com/adobecom/milo/pull/503) and SHOULD NOT be merged until the PR in milo is merged and then consumed here.
* Updates all CSS rules to use lowercase t-shirt sizes
* Updates all JS files that set classnames to use lowercase t-shirt sizes
* Should allow us to get a clearer picture of style-linting errors moving forward
Resolves: [MWPW-126441](https://jira.corp.adobe.com/browse/MWPW-126441)
**Test URLs:**
(Note that these should both look the same, but the After view uses lowercase t-shirt size classnames)
- Before: https://main--bacom--adobecom.hlx.page/docs/library/blocks/stats?martech=off
- After: https://ebartholomew-kebab-case-tshirts--bacom--adobecom.hlx.page/docs/library/blocks/stats?martech=off
=> [MWPW-126441] Unblock style-linting by lowercasing all t-shirt sizes in classnames

scripts/scripts.js
Resolves: [MWPW-127111](https://jira.corp.adobe.com/browse/MWPW-127111)
Dependent on https://github.com/adobecom/milo/pull/512
**Test URLs:**
- After: https://htmlexclude--bacom--adobecom.hlx.page/?martech=off
=> MWPW-127111 Exclude blog links from being htmlized

helix-query.yaml
* Adding breadcrumb home to german query index
* (Only doing one geo first to check that it works)
Resolves: [MWPW-129144](https://jira.corp.adobe.com/browse/MWPW-129144)
**Test URLs:**
N/A
=> MWPW-129144 Breadcrumb home report - de

scripts/scripts.js
* Organizing styles by block name and only loading block styles as needed.
* You should see two faas.css files loaded from libs/ and styles/
* More styles to come, see: [MWPW-128620](https://jira.corp.adobe.com/browse/MWPW-128620), [MWPW-129587](https://jira.corp.adobe.com/browse/MWPW-129587), and [MWPW-129585](https://jira.corp.adobe.com/browse/MWPW-129585)
Resolves: [MWPW-128620](https://jira.corp.adobe.com/browse/MWPW-128620)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/resources/6-must-haves-fast-flexible-ecommerce-platform?martech=off
- After: https://bmarshal-faas-1-col--bacom--adobecom.hlx.page/resources/6-must-haves-fast-flexible-ecommerce-platform?martech=off
=> MWPW-128620 loading block styles

styles/faas.css
* Adds FaaS Clearbit Enabled styles based on work expected to be merged into milo: https://github.com/adobecom/milo/pull/686
Resolves: [MWPW-129585](https://jira.corp.adobe.com/browse/MWPW-129585)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/slavin/faas-pages/forrester-wave-copy?martech=off
- After: https://clearbit-faas-next-styles--bacom--adobecom.hlx.page/drafts/slavin/faas-pages/forrester-wave-copy?martech=off
=> MWPW-129397 Clearbit FaaS Enabled Styles

helix-query.yaml
* Update the selector for the US Resource index to allow for text blocks that don't have "contained"
Resolves: [MWPW-130076](https://jira.corp.adobe.com/browse/MWPW-130076)
**Test URLs:**
N/A
=> MWPW-130076 Resource Index Text Selector

scripts/scripts.js
When there are multiple images in the marquee at the top of the page, only the first image in the marquee is eager loaded.  In many cases the first image is a very small image and the 2nd image is the main background image, which should also be eager loaded.
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/customer-success-stories/helly-hansen-case-study?martech=off
- After: https://c3-eager--bacom--adobecom.hlx.page/customer-success-stories/helly-hansen-case-study?martech=off
To test:
* Inspect the HH logo in the marquee.  In both branches that is eager loaded
* Inspect the skier image in the marquee.  In main the image is lazy loaded, in c3-eager the image is now eager loaded.
=> Eager load all marquee images

helix-query.yaml
* Add /why-adobe and /support folders to sitemap index
Resolves: [MWPW-133230](https://jira.corp.adobe.com/browse/MWPW-133230)
**Test URLs:**
N/A
=> MWPW-133230 Add why-adobe and support to sitemap

helix-query.yaml
- Add /why-adobe and /support folders to US sitemap index
- Follow up from #126 
Resolves: [MWPW-133230](https://jira.corp.adobe.com/browse/MWPW-133230)
Test URLs:
N/A
=> MWPW-133230 why-adobe and support for US sitemap

styles/styles.css
* Adds two classes to styles.css as overrides for CaaS min-height in section metadata. 
* The small class represents roughly the height of the half cards, the medium the full sized cards. 
After doing some investigation, essentially loading the footer after CaaS cards load would require a change against the CaaS react components themselves, and may not be the best approach. The CaaS react component mounts to the DOM before the cards are finished fetching, and the CaaS component itself is controlled by the CaaS react components, meaning that though we could ask for an event to be added, there may occur situations in which the footer would not load.  In addition to this, since the footer is loaded in `loadArea()` changes to prevent CLS on this page would require a change that could have …
=> MWPW-133167 CaaS CLS Issue

scripts/scripts.js
* Updating the html exclude regular expression to include /blog with no trailing slash
* Previously `appendHtmlPostfix` was only called durring `loadArea`, but now that html postfix has been updated   `appendHtmlToLink` is called more frequently with `decorateLinks`.  https://github.com/adobecom/milo/pull/927
* The Experience Cloud blog, https://business.adobe.com/blog, does not have a trailing slash and since gnav is loading fragments, fragments/gnav/resources.plain.html, the `appendHtmlToLink` function is now ran against the blog link.
* Note, stage works correctly because the domains do not match.
Resolves: [MWPW-134103](https://jira.corp.adobe.com/browse/MWPW-134103)
**Test URLs:**
N/A
=> MWPW-134103 Fix Blog Regex

helix-query.yaml
* Update indexes for content launch
Resolves: [MWPW-134578](https://jira.corp.adobe.com/browse/MWPW-134578)
**Test URLs:**
N/A
=> MWPW-134578 Update indexes for content launch

scripts/scripts.js
Set the `useDotHtml` flag for all of bacom.
Requires this milo pr: https://github.com/adobecom/milo/pull/1148
Resolves: [MWPW-135447](https://jira.corp.adobe.com/browse/MWPW-135447)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/?milolibs=homehtml&martech=off
- After: https://usedothtml--bacom--adobecom.hlx.page/?milolibs=homehtml&martech=off
=> MWPW-135447 Use .html for all bacom links

styles/faas.css
* Fix resource-center styling on faas forms to allow centered title
Resolves: [MWPW-135371](https://jira.corp.adobe.com/browse/MWPW-135371)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/drafts/atierney/test1?martech=off
- After: https://methomas-faas-heading--bacom--adobecom.hlx.live/drafts/atierney/test1?martech=off
For regression:
- https://methomas-faas-heading--bacom--adobecom.hlx.page/
- https://methomas-faas-heading--bacom--adobecom.hlx.page/resources/reports/gartner-mq-personalization-engines-2023
=> MWPW-135371 FaaS title center

styles/styles.css
* Fixes grid issues caused by milo PR https://github.com/adobecom/milo/pull/1259
* Overwrites section metadata grid styles to conform to how it was before milo PR
Resolves: [MWPW-136934](https://jira.corp.adobe.com/browse/MWPW-136934)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/products/analytics/adobe-analytics-benefits
- After: https://methomas-grid-bug--bacom--adobecom.hlx.live/products/analytics/adobe-analytics-benefits?martech=off
- Before:  https://main--bacom--adobecom.hlx.live/products/campaign/benefits
- After: https://methomas-grid-bug--bacom--adobecom.hlx.live/products/campaign/benefits?martech=off
- Before: https://main--bacom--adobecom.hlx.live/products/experience-manager/digital-commerce
- After: …
=> MWPW-136934 Grid Bug

tools/sidekick/config.json
* Add links to CaaS and FaaS configurator to the sidekick
* Link to these configurators has been added under Tools
* Configurator page will open in a new tab in browser
Resolves: [MWPW-134192](https://jira.corp.adobe.com/browse/MWPW-134192)
**Test URLs:**
- After: https://sidekick--bacom--ruchika4.hlx.page/?martech=off
=> MWPW-134192-Add caas and faas configurator to sidekick

scripts/scripts.js
* Only load all images if the marquee has a split variant
Resolves: [MWPW-139001](https://jira.corp.adobe.com/browse/MWPW-139001)
---
- [Before](https://main--bacom--adobecom.hlx.live/customer-success-stories/helly-hansen-case-study?martech=off)
- [After](https://fix-eager-lcp--bacom--adobecom.hlx.live/customer-success-stories/helly-hansen-case-study?martech=off)
Observe there are two images loading in the network console...
---
- [Before](https://main--bacom--adobecom.hlx.live/drafts/cmillar/aem-trials?martech=off)
- [After](https://fix-eager-lcp--bacom--adobecom.hlx.live/drafts/cmillar/aem-trials?martech=off)
Observe there are two images loading in the network console...
Observe there is only one image loading in the network console...
=> MWPW-139001 - Adjust LCP Image Loading

helix-query.yaml
* Change format of publish date in query index to a string rather than date value. This is because some site sections have different date formats (MM-DD-YYYY vs YYYY-MM-DD)
Resolves: [MWPW-138379](https://jira.corp.adobe.com/browse/MWPW-138379)
**Test URLs:**
N/A
=> MWPW-138379 Query index date format

scripts/scripts.js
* Do not blindly select the first image for LCP if there is a vanilla marquee
* Maintain split marquee all image eager loading
* Maintain fallback to non-marquee first document image eager loading
Resolves: [MWPW-141663](https://jira.corp.adobe.com/browse/MWPW-141663)
**Test URLs:**
- After: https://auniverseaway-patch-7--bacom--adobecom.hlx.live/?martech=off
=> MWPW-141663 - Fix BACOM Homepage Marquee LCP

.github/workflows/fg-sync-repos.yml
The sidekick in the pink project will be slightly different and should be ignored from getting overwritten when the git repo sync is performed. For example: The endpoint to load the Milo Localization v2 will be different for pink project.
Resolves: [MWPW-142098](https://jira.corp.adobe.com/browse/MWPW-142098)
=> MWPW-142098: Ignore pink sidekick config during sync

scripts/utils.js, test/scripts/utils.test.js
* Modifies existing function to be in line with milo-college's format. 
* Adds unit tests for setLibs from milo-college
* Adds stage specific unit tests 
Question: 
Do we want "stage--bacom--adobecom.hlx.page/live" urls to point to milo stage? Currently this code has those hosts point to main milo libs. 
Resolves: [MWPW-142290](https://jira.corp.adobe.com/browse/MWPW-142290)
**Test URLs:**
- After: https://update-libs-stage--bacom--adobecom.hlx.live/?martech=off
=> MWPW-142290: Update get/setLibs for stage

scripts/utils.js, test/scripts/utils.test.js
* Updating our current libs patterns to match Milo College.
* Removing the stage logic and tests as they are not needed
Resolves: [MWPW-142290](https://jira.corp.adobe.com/browse/MWPW-142290)
**Test URLs:**
- After: https://revert-stage-libs-updates--bacom--adobecom.hlx.live/?martech=off
=> MWPW-142290: Reverting Libs Stage Updates

styles/styles.css
* Removes `display: block` and resets two properties for the classes effected. 
Context: 
Display block is overriding the styles that Milo implements to prevent CLS. However, due to previous issues that occur with the `grid-width` classes, these styles were added to insure b.a.com pages did not break. There is a current PR to fix this in Milo, which would then necessitate us removing some of the code that was part of our hotfix. 
However, when attempting to remove some of the hotfix CSS it caused issues on other pages where the CLS issue was observed. Until the changes in Milo get verified and then merged, we may need to keep the hotfix code in place. 
See these PRs:
- https://github.com/adobecom/milo/pull/1881
- https://github.com/adobecom/bacom/pull/155
- …
=> MWPW-143973: CLS Issue with Grid Width

blocks/stats/stats.js, scripts/scripts.js, scripts/utils.js, styles/styles.css, tools/sidekick/config.js
* Remove unnecessary apache license information
Resolves: [MWPW-143582](https://jira.corp.adobe.com/browse/MWPW-143582)
**Test URLs:**
- After: https://methomas-copyright--bacom--adobecom.hlx.live/?martech=off
=> MWPW-143582 Remove copyright comments

.kodiak/config.yaml
Creates file required for MWPW-143708 and MWPW-143712
Resolves: 
- [MWPW-143708](https://jira.corp.adobe.com/browse/MWPW-143708)
- [MWPW-143712](https://jira.corp.adobe.com/browse/MWPW-143712)
**Test URLs:**
- After: https://thedoc31-patch-1--bacom--adobecom.hlx.live/?martech=off
=> MWPW-143708: Create Kodiak config.yaml

.kodiak/config.yaml
* Team assignment value was not working per Jed's testing, changed to actual team name which is validated working for Javelin. Updating Magma to match.
Resolves: 
- [MWPW-143712](https://jira.corp.adobe.com/browse/MWPW-143712)
- [MWPW-143708](https://jira.corp.adobe.com/browse/MWPW-143708)
**Test URLs:**
- After: https://thedoc31-patch-1--bacom--adobecom.hlx.live/?martech=off
=> Fix team assignment

.github/workflows/graybox-sync-repos.yml
The enhancement handles stage-to-stage branch sync. This is to cater the recent change where all milo repos have defaulted to stage branch.
Resolves: [MWPW-145870](https://jira.corp.adobe.com/browse/MWPW-145870)
=> MWPW-145870: Graybox sync enhancement

.hlxignore
* Update .hlxignore to remove root json
Files that should 404 package.json & web-test-runner.config.mjs
https://main--bacom--adobecom.hlx.live/package.json
https://bmarshal-hlxignore--bacom--adobecom.hlx.live/package.json
https://main--bacom--adobecom.hlx.live/web-test-runner.config.mjs
https://bmarshal-hlxignore--bacom--adobecom.hlx.live/web-test-runner.config.mjs
Files that should 200 tools/sidekick/config.json
https://main--bacom--adobecom.hlx.live/tools/sidekick/config.json
https://bmarshal-hlxignore--bacom--adobecom.hlx.live/tools/sidekick/config.json
Resolves: [MWPW-145787](https://jira.corp.adobe.com/browse/MWPW-145787)
**Test URLs:**
- After: https://bmarshal-hlxignore--bacom--adobecom.hlx.live/?martech=off
=> MWPW-145787 Update .hlxignore

.github/workflows/auto-merge-main-to-stage.yml
* Adds the GH workflow from milo for syncing main -> stage after a push to main.
**Test URLs:**
- After: https://stage--bacom--adobecom.hlx.live/?martech=off
=> Issue #196: Add main -> stage sync workflow

scripts/scripts.js
Resolves: [MWPW-145574](https://jira.corp.adobe.com/browse/MWPW-145574)
**Test URLs:**
- After: https://dynamic-nav-config--bacom--adobecom.hlx.live/?martech=off
=> MWPW-145574: Adding dynamicNavKey to config

scripts/utils.js
This PR extends the nonprod hostnames check that determines if the `milolibs` query parameter is allowed.
Resolves: [MWPW-150667](https://jira.corp.adobe.com/browse/MWPW-150667)
**Test URLs:**
- After: https://main--bacom--adobecom.hlx.live/?martech=off&milolibs=darth-vader--milo--robert-bogos
=> [MWPW-150667] - milolibs query parameter not working

scripts/scripts.js
Get a more [detailed signal for 404 pages](https://adobe-mwp.slack.com/archives/C0749KS9F8X/p1717077243972919).
Implements consumer changes for https://github.com/adobecom/milo/pull/2448
Resolves: [MWPW-152132](https://jira.corp.adobe.com/browse/MWPW-152132)
Going to a 404 page should have a weight of 10 for `window.hlx.rum.weight` once the milo PR is merged. (This BACOM-PR can be merged already without any influence)
**Test URLs:**
- After: https://increase-404-tracking--bacom--adobecom.hlx.live/?martech=off
=> Increase 404 tracking

.github/workflows/fg-sync-repos.yml
* https://github.com/adobecom/bacom/pull/206
* https://github.com/adobecom/bacom/pull/207
=> [Release] Stage to Main

scripts/scripts.js
**Description**
This PR adds the `stageDomainsMap` to the config allowing links to be environment-aware.
More about this new feature can be found in [here](https://github.com/orgs/adobecom/discussions/2437).
Resolves: [MWPW-151457](https://jira.corp.adobe.com/browse/MWPW-151457)
=> [MWPW 151457] Added stage domains map to make links environment-aware

scripts/scripts.js
* Remove stage mapping (revert #205 )
Resolves: [MWPW-153603](https://jira.corp.adobe.com/browse/MWPW-153603)
Related: [MWPW-153692](https://jira.corp.adobe.com/browse/MWPW-153692)
**Test URLs:**
**CTA link:**
- Before: https://main--bacom--adobecom.hlx.page/in/products/marketo/attribution?martech=off
- After: https://methomas-remove-mapping--bacom--adobecom.hlx.page/in/products/marketo/attribution?martech=off
Scroll down to "Grow leads without growing your marketing spend." => Read report. 
Should link to: https://business.adobe.com/resources/reports/the-total-economic-impact-of-bizible.html 
Not the stage link: https://business.stage.adobe.com/resources/reports/the-total-economic-impact-of-bizible.html
**PDF Viewer:**
- Before: …
=> MWPW-153603 Remove stage mapping

styles/styles.css
Reverts adobecom/bacom#224
Test URLs:
- Before: https://main--bacom--adobecom.hlx.live/resources/videos/marketo-product-tour?martech=off
- After: https://revert-224-bmarshal-marketo-margin--bacom--adobecom.hlx.live/resources/videos/marketo-product-tour?martech=off
=> Revert "MWPW-154562 Fix resource form margins"

scripts/scripts.js
* Update India lang code from “en-GB” to “en-IN” to fix Marketo form privacy link mapping.
To verify, check the top HTML lang value.
Resolves: [MWPW-154250](https://jira.corp.adobe.com/browse/MWPW-154250)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/in/?martech=off
- After: https://bmarshal-in-lang--bacom--adobecom.hlx.live/in/?martech=off
=> MWPW-154250 Update India lang code

head.html
* Adds the setlibs function and some code in a script tag in the head to preload assets for the pages to increase loading speed. 
Resolves: [MWPW-154060](https://jira.corp.adobe.com/browse/MWPW-154060)
**Test URLs:**
- After: https://head-prefetch-test--bacom--adobecom.hlx.live/?martech=off
=> MWPW-154060: Preload most used scripts in head.html

scripts/aa-university.js, test/scripts/aa-university.test.js, test/scripts/mocks/with-group.html
* Adds the ability to add a `sanboxgroup` metadata to the page that will send this group along with the post request. 
Context: 
This will allow for us to use this endpoint for multiple uses in the interim while we get a runtime solution up and running.  Arnfried has made the endpoint default to the original sandbox group if no group is sent with the POST request. This means by default we do not want to send a group unless it is found in the metadata. Additionally, probably a good idea for the authors to add the metadata `sandboxGroup` to the og page to have authoring parity. 
Needs to be tested with Eric. 
Resolves: [MWPW-NUMBER](https://jira.corp.adobe.com/browse/MWPW-154363)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/drafts/slavin/adobe-analytics-sandbox?martech=off …
=> MWPW-154363: Add param anaylitics sandbox

blocks/chat-cta/chat-cta.css
* Small CSS changes to fix layout issues 
Resolves: [MWPW-160549](https://jira.corp.adobe.com/browse/MWPW-160549)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.live/drafts/slavin/chat-cta-examples/cta-included?martech=off
- After: https://chat-cta-styles--bacom--adobecom.hlx.live/drafts/slavin/chat-cta-examples/cta-included?martech=off
=> MWPW-160549: Chat CTA bug fixes

404.html, scripts/redirects.js
- add smart redirects for (temporary) client-side redirects
this is a port of https://github.com/adobe/helix-website/pull/671 and https://github.com/adobe/helix-website/pull/670
from www.aem.live to bacom, see discussion in https://adobe.enterprise.slack.com/archives/C0749KS9F8X
Resolves: [MWPW-133726](https://jira.corp.adobe.com/browse/MWPW-133726)
**Test URLs**
Simple Redirect
- Before: https://main--bacom--adobecom.hlx.page/drafts/methomas/page-does-not-exist
- After: https://smart-redirects--bacom--adobecom.hlx.page/drafts/methomas/page-does-not-exist
- Should redirect to: https://smart-redirects--bacom--adobecom.hlx.page/drafts/methomas/smart-redirects-end/page-1?redirect_from=%2Fdrafts%2Fmethomas%2Fpage-does-not-exist
One parameter redirect
- Before: …
=> MWPW-133726 add smart redirects for (temporary) client-side redirects

scripts/redirects.js
- stripping .html from the pathname for smart-redirects
Resolves: [MWPW-161697](https://jira.corp.adobe.com/browse/MWPW-161697)
**Test URLs:**
(Can only test .html on stage)
- https://business.stage.adobe.com/au/products/experience-manager/assets/adobe-asset-link.html
=> MWPW-161697 Fix smart redirects .html issue

scripts/redirects.js
* Increase the smart redirect limit from the default (1,000) to 100,000 entries
Resolves: [MWPW-161696](https://jira.corp.adobe.com/browse/MWPW-161696)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/uk/products/experience-manager/assets/rich-media-delivery
- After: https://methomas-redirect-limit--bacom--adobecom.hlx.page/uk/products/experience-manager/assets/rich-media-delivery
=> MWPW-161696 Increase smart redirect entry limit

scripts/scripts.js
* Adds graybox to stageDomainMap 
Resolves: [MWPW-162887](https://jira.corp.adobe.com/browse/MWPW-162887)
**Test URLs:**
- After: https://update-stage-domain-map--bacom--adobecom.hlx.live/?martech=off
=> MWPW-162887: Adding graybox to stageDomainMap

.github/workflows/import/constants.js, .github/workflows/import/converters.js, .github/workflows/import/daFetch.js, .github/workflows/import/index.js, .github/workflows/import/package-lock.json, .github/workflows/import/package.json, .github/workflows/listen-to-publish-events.yaml, .gitignore
Enables a rolling import to DA based on Nexters import script with small adaptions for IMS. Since this is a copy, we'll need to manually sync any updates that go into the nexter import script
- Workflow gets notified on publish on bacom
- Workflow imports the published resource to DA da-bacom
- Workflow previews & publishes that resource
Resolves: [MWPW-164826](https://jira.corp.adobe.com/browse/MWPW-164826)
**Test URLs:**
- Before: https://stage--bacom--adobecom.hlx.live/?martech=off
- After: https://da-rolling-import--bacom--adobecom.hlx.live/?martech=off
=> Rolling import to DA

tools/sidekick/config.json
* Returns loc sidekick urls to previous state because loc is not yet ready for helix 5
**Test URLs:**
- After: https://hlx-5--bacom--adobecom.aem.live/?martech=off
=> MWPW-166673 Helix 5 upgrade fix - revert loc sidekick urls

scripts/scripts.js
* Fix PDFs not showing up on hlx.page and hlx.live
**Test URLs:**
- After: https://hlx5-pdf--bacom--meganthecoder.hlx.page/drafts/methomas/pdf-viewer-bacom-milo-link?martech=off
(PDF will show an error because the test url isn't allowlisted)
=> MWPW-166673 Hlx 5 upgrade - revert pdf client ids

tools/sidekick/config.json
* Remove `.aem.` urls from sidekick
* URLs generated upon preview should be `hlx.page` (To test, you need to set the local project configuration in the old sidekick to: https://hlx5-sidekick--bacom--adobecom.hlx.live)
* Sidekick tools should not have `.aem.` links. Will be prod or hlx urls.
**Test URLs:**
- After: https://hlx5-sidekick--bacom--adobecom.hlx.live/?martech=off
- After: https://hlx5-sidekick--bacom--adobecom.aem.live/?martech=off
=> MWPW-166673 [Helix 5 Migration] Revert sidekick config

tools/sidekick/config.json
* Explicitly set the sidekick preview and live link config to `.hlx.`
* Will have no change for authors
* Allows us to control the change from `.hlx.` to `.aem.` in sidekick instead of it being inferred from the config
**Test URLs:**
- Before: https://main--bacom--meganthecoder.hlx.live/?martech=off
- After: https://hlx5-preview-link--bacom--meganthecoder.hlx.live/?martech=off
*Need to test with the advanced local configuration in sidekick
=> MWPW-166673 [Helix 5 Migration] Set preview url

scripts/scripts.js
* Update PDF Viewer client ids to support all domains, including aem.page and aem.live
Resolves: [MWPW-167216](https://jira.corp.adobe.com/browse/MWPW-167216)
**Test URLs:**
- Before: https://main--bacom--adobecom.aem.live/drafts/methomas/pdf-bacom-prod?martech=off
- After: https://pdf-aem--bacom--adobecom.aem.live/drafts/methomas/pdf-bacom-prod?martech=off
Note: This is not testable pre-production.
=> MWPW-167216 Configure pdf for aem domains

scripts/scripts.js
* Correct jarvis id by removing spaces
Resolves: [MWPW-168712](https://jira.corp.adobe.com/browse/MWPW-168712)
**Test URLs:**
- After: https://stage--bacom--adobecom.aem.live/?martech=off
Note: This is not testable before stage because of domain allowlisting
=> MWPW-168712 Jarvis Chat - remove spaces

scripts/scripts.js
* Correct jarvis chat id
Resolves: [MWPW-168712](https://jira.corp.adobe.com/browse/MWPW-168712)
**Test URLs:**
- After: https://jarvis--bacom--meganthecoder.aem.live/?martech=off
*This is not testable on a feature branch
=> MWPW-168712 Fix Jarvis ID

styles/styles.css
We have styled the sign-in button to matched with UNAV sign in button stylings. This change is only needed for the Bacom sign-in button since Bacom does not use the UNAV. Therefore, we applied this change specifically within the Bacom codebase.
Before:
After:
Resolves: [MWPW-167349](https://jira.corp.adobe.com/browse/MWPW-167349)
**Test URLs:**
- After: https://mwpw-167349--bacom--adobecom.aem.live/?martech=off
=> Added singn in button style similar like for unav sign in button

helix-sitemap.yaml
* Update BACOM Blog sitemap references
* Remove KR Blog sitemap reference
* https://github.com/adobecom/da-bacom-blog/pull/25
Resolves: [MWPW-162451](https://jira.corp.adobe.com/browse/MWPW-162451)
**Test URLs:**
- After: https://bmarshal-da-blog-sitemap--bacom--adobecom.aem.live/?martech=off
=> MWPW-162451 Update blog sitemap

.github/workflows/auto-merge-main-to-stage.yml, .github/workflows/code-compatibility.yaml, .github/workflows/codeql.yml, .github/workflows/fg-sync-repos.yml, .github/workflows/graybox-sync-repos.yml, .github/workflows/listen-to-publish-events.yaml, .github/workflows/run-e2e-daily.yaml, .github/workflows/run-lint.yml, .github/workflows/run-nala.yaml, .github/workflows/run-tests.yaml
Following this [incident](https://www.wiz.io/blog/github-action-tj-actions-changed-files-supply-chain-attack-cve-2025-30066) we want to harden the security for our Github actions by [pinning actions](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) to full length commit SHAs. Its the recommended approach in terms of security from Github and while we won't get any minor versions OOTB, security and stability is more important than the latest and greatest features in this case.
Resolves: [MWPW-169978](https://jira.corp.adobe.com/browse/MWPW-169978)
Actions
Checkout https://github.com/actions/checkout/commit/11bd71901bbe5b1630ceea73d27597364c9af683
CodeQL …
=> MWPW-166978: Harden github workflows

.github/workflows/listen-to-publish-events.yaml
* Adds the correct hash for setup-node since current hash was failing 
**Test URLs:**
- After: https://stage--bacom--adobecom.aem.live/?martech=off
=> Fixing workflow bug

tools/sidekick/config.json
* Update preview url and tools urls in sidekick from `.hlx.` to `.aem.`
**Test URLs:**
- After: https://sidekick-aem--bacom--adobecom.aem.live/?martech=off
=> MWPW-166673 [Helix 5 Migration] Update sidekick urls

scripts/scripts.js
* Update lana endpoint to the new bacom proxy
* Should fix referer issue (only testable on stage and prod)
Resolves: [MWPW-169850](https://jira.corp.adobe.com/browse/MWPW-169850)
**Test URLs:**
- Before: https://main--bacom--adobecom.aem.live/drafts/methomas/404-monitoring?lanadebug=on
- After: https://lana-proxy--bacom--adobecom.aem.live/drafts/methomas/404-monitoring?lanadebug=on
=> MWPW-169850 Update lana endpoint

scripts/scripts.js, test/scripts/mocks/hero-marquee-by-device.html, test/scripts/mocks/marquee-by-device.html, test/scripts/mocks/marquee-foreground.html, test/scripts/mocks/marquee.html, test/scripts/mocks/section.html, test/scripts/scripts.test.js
* Enable support for background image by device
* Enable support for hero marquee
* Enable support for section background image
Resolves: [MWPW-170869](https://jira.corp.adobe.com/browse/MWPW-170869) and  [MWPW-170918](https://jira.corp.adobe.com/browse/MWPW-170918)
**Test URLs:**
Hero marquee:
- Before: https://main--bacom--adobecom.aem.live/products/experience-manager/sites/optimizer?martech=off
- After: https://lcp-aep--bacom--meganthecoder.aem.live/products/experience-manager/sites/optimizer?martech=off
Marquee (now with background image by device):
- Before: https://main--bacom--adobecom.aem.page/drafts/methomas/marquee-bg-img-by-device?martech=off
- After: https://lcp-aep--bacom--meganthecoder.aem.page/drafts/methomas/marquee-bg-img-by-device?martech=off
Section with background …
=> MWPW-170869 MWPW-170918 Update LCP Image Selection

styles/styles.css
* Remove code that prevented left/right spacing on mobile and tablet when section metadata has `grid-width-*` classes
Resolves: [MWPW-161864](https://jira.corp.adobe.com/browse/MWPW-161864)
**Test URLs:**
- Before: https://main--bacom--adobecom.hlx.page/drafts/mkhare/grid-width-8
- After: https://grid-8--bacom--meganthecoder.hlx.page/drafts/mkhare/grid-width-8
**Note:** We've tried to address grid widths before (#151 , #155) and it's very prone to causing regression issues. This should be tested broadly
Regression:
Homepage:
- After: https://grid-8--bacom--meganthecoder.aem.live/?martech=off
Holiday Report:
- Before: https://main--bacom--adobecom.aem.live/resources/holiday-shopping-report?martech=off
- After: …
=> MWPW-161864 Fix grid width mobile gutters

.github/workflows/import/daFetch.js, .github/workflows/import/index.js
Don't error for when we don't find assets. Erroring will currently stop the process, but if we try to import something from production - which is already available elsewhere (e.g. AEM Assets or old AEM) - we can safely ignore these errors and simply notify us on slack.
**Test URLs:**
- After: https://dont-error-when-not-finding-assets--bacom--adobecom.aem.live/?martech=off
=> Dont error for unfound assets for the auto importer

.github/workflows/import/index.js
Fixes SVG imports https://github.com/da-sites/nexter/pull/48 that have URLs attached to them. Resolves: [MWPW-173538](https://jira.corp.adobe.com/browse/MWPW-173538)
Also a few improvements that were done in the same breath:
- Don't add slack messages for trying to import redirected assets
- Safeguard _in-case_ media cant be imported and just log it
- Add code to `safeguardMetadataImages` _if needed_ .. currently commented out.
- Exclude import metadata, metadata-seo alongside redirects
**Test URLs:**
- After: https://fix-svg-imports--bacom--adobecom.aem.live/?martech=off
=> Fix SVG imports with a link

head.html
* Adds code that accounts for locales, and utilizes the locale string to be more deterministic about the block of links
Resolves: [MWPW-173464](https://jira.corp.adobe.com/browse/MWPW-173464)
**Test URLs:**
- After: https://fix-hreflang-issue--bacom--adobecom.aem.page/fr/drafts/slavin/aem-sites?martech=off
=> MWPW-173464: Fix hreflang issue

scripts/scripts.js, test/blocks/cta-widget/cta-widget.test.js, test/scripts/scripts.test.js
* Adds custom language link transformation for experienceleague.adobe.com links on bacom
* Updates cta widget tests to fix failures
Resolves: [MWPW-167454](https://jira.corp.adobe.com/browse/MWPW-167454)
**Test URLs:**
CN
- Before: https://main--bacom--adobecom.aem.live/cn/drafts/methomas/experienceleague?martech=off
- After: https://experience-league--bacom--meganthecoder.aem.page/cn/drafts/methomas/experienceleague?martech=off
CA_FR
- Before: https://main--bacom--adobecom.aem.live/ca_fr/drafts/methomas/experienceleague?martech=off
- After: https://experience-league--bacom--meganthecoder.aem.page/ca_fr/drafts/methomas/experienceleague?martech=off
DE
- Before: https://main--bacom--adobecom.aem.live/de/drafts/methomas/experienceleague?martech=off
- After: …
=> MWPW-167454 Localize Experience League Links
